# Generated by Django 4.1.6 on 2023-04-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorpostures',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
