# Generated by Django 4.1.6 on 2023-04-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_poorpostures_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
