# Generated by Django 4.1.6 on 2023-04-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_poorpostures_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='videos',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
